//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CkEditorExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCkEditor
    {
        public int Id { get; set; }
        public string PostTitle { get; set; }
        public string PostComment { get; set; }
    }
}
